import { sha256 } from "../../shared/canonical-json.js";
import type { RepositoryAnalysisV2,SourceRef } from "../../analysis/v2/model.js";
import { ASTER_RECIPE } from "./archetypes/aster.js";
import { botanicalSceneV2Schema,type BotanicalSceneV2,type ProvenanceV2 } from "./model.js";
import { sampleVariation,type VariationRange } from "./variation.js";

export type BotanicalV2Options={structuralSeed?:string;decorativeSeed?:string;scalingMode?:"repository-relative"|"globally-comparable"};
type EvidenceId="phenotype.stature"|"phenotype.foliation.testing"|"phenotype.foliation.documentation"|"episode.salience.release";
const vr=(min:number,max:number,concern:string,kind:"structural"|"decorative"="decorative"):VariationRange=>({min,max,distribution:"triangular",concern,class:kind});
const uniq=(r:SourceRef[])=>[...new Map(r.map(x=>[`${x.kind}:${x.id}`,x])).values()].sort((a,b)=>a.kind.localeCompare(b.kind)||a.id.localeCompare(b.id));
export function interpretAster(a:RepositoryAnalysisV2,o:BotanicalV2Options={}):BotanicalSceneV2{
 if(!a.episodes.length)throw new Error("Botanical Scene v2 requires at least one development episode");
 const seedBasis=`${a.source.configHash}\0${a.source.snapshotSha}\0botanical-grammar-v2.0.0\0aster-v1\0xoshiro128ss-v1`,structuralSeed=o.structuralSeed??sha256(`${seedBasis}\0structural`),decorativeSeed=o.decorativeSeed??sha256(`${seedBasis}\0decorative`),episodes=a.episodes,first=episodes[0]!,last=episodes.at(-1)!;
 const prov=(ids:string[],rule:string,metrics:EvidenceId[]=[]):ProvenanceV2=>{const es=episodes.filter(e=>ids.includes(e.id)),inputs=uniq(es.flatMap(e=>e.sourceRefs)),resolve=(metricId:EvidenceId):number=>{switch(metricId){case"phenotype.stature":return a.phenotype.axes.stature.value;case"phenotype.foliation.testing":return a.phenotype.axes.foliation.testing.value;case"phenotype.foliation.documentation":return a.phenotype.axes.foliation.documentation.value;case"episode.salience.release":return es.length===1?es[0]!.salience.release:Math.max(...es.map(e=>e.salience.release));}};return{sourceRefs:inputs,metricRefs:metrics.map(metricId=>({metricId,value:resolve(metricId),normalization:"repository-relative" as const,inputs})),summaryRef:ids.join(","),derivation:rule,confidence:Math.min(...es.map(e=>e.provenance.confidence)),capabilities:a.capabilities};};
 const pIndex:Record<string,ProvenanceV2>={},put=<T extends{id:string;provenance:ProvenanceV2}>(x:T)=>{pIndex[x.id]=x.provenance;return x;};
 const mainNodes=episodes.map((e,i)=>put({id:`node-${String(i+1).padStart(2,"0")}`,axisId:"axis-main",arcPosition:(i+1)/(episodes.length+1),episodeId:e.id,organIds:[] as string[],provenance:prov([e.id],"aster-v1:growth-node-from-episode")}));
 const attachment=(i:number,axis="axis-main")=>({parentAxisId:axis,arcPosition:mainNodes[Math.min(i,mainNodes.length-1)]!.arcPosition,tangentAngle:0,side:(i%2?"right":"left") as "left"|"right",nodeId:mainNodes[Math.min(i,mainNodes.length-1)]!.id});
 const released=episodes.filter(e=>e.status==="released").sort((x,y)=>y.salience.release-x.salience.release).slice(0,2),unreleased=episodes.filter(e=>e.status==="unreleased").sort((x,y)=>y.salience.volume-x.salience.volume),flowerEpisodes=released.length?released:[last];
 const axes:any[]=[]; const mainProv=prov(episodes.map(e=>e.id),"aster-v1:chronological-main-axis",["phenotype.stature"]);axes.push(put({id:"axis-main",kind:"main-stem" as const,chronology:{startEpisodeId:first.id,endEpisodeId:last.id},length:.7+a.phenotype.axes.stature.value*.3,baseRadius:.06,tipRadius:.012,taperExponent:1.3,lean:(a.phenotype.axes.collaboration.value-.5)*.15,curvature:.1+a.phenotype.axes.seasonality.value*.2,nodeIds:mainNodes.map(n=>n.id),supportsFeatureIds:[],variation:{waviness:vr(-.08,.08,"stem-waviness"),bend:vr(-.06,.06,"stem-bend","structural"),torsion:vr(-.04,.04,"stem-torsion")},provenance:mainProv}));
 const rootIds=["axis-root",...Array.from({length:4},(_,i)=>`axis-root-lateral-${i+1}`)],rootNodes=Array.from({length:4},(_,i)=>put({id:`node-root-${i+1}`,axisId:"axis-root",arcPosition:.2+i*.16,episodeId:first.id,organIds:[rootIds[i+1]!],provenance:prov([first.id],"aster-v1:lateral-root-attachment-node")}));axes.push(put({id:"axis-root",kind:"root" as const,chronology:{startEpisodeId:first.id,endEpisodeId:last.id},length:.45,baseRadius:.055,tipRadius:.008,taperExponent:1.5,lean:0,curvature:.12,nodeIds:rootNodes.map(x=>x.id),supportsFeatureIds:rootIds.slice(1),variation:{waviness:vr(-.1,.1,"root-waviness"),bend:vr(-.1,.1,"root-bend","structural"),torsion:vr(-.03,.03,"root-torsion")},provenance:prov(episodes.map(e=>e.id),"aster-v1:activity-continuity-root-system")}));
 for(let i=0;i<4;i++)axes.push(put({id:rootIds[i+1]!,kind:"lateral-root" as const,parentAttachment:{parentAxisId:"axis-root",arcPosition:.2+i*.16,tangentAngle:0,side:(i%2?"right":"left") as "left"|"right",nodeId:rootNodes[i]!.id},chronology:{startEpisodeId:first.id,endEpisodeId:last.id},length:.18+i*.02,baseRadius:.018,tipRadius:.002,taperExponent:1.4,lean:0,curvature:.15,nodeIds:[],supportsFeatureIds:[],variation:{waviness:vr(-.15,.15,"root-waviness"),bend:vr(-.1,.1,"root-bend","structural"),torsion:vr(-.03,.03,"root-torsion")},provenance:prov([first.id],"aster-v1:lateral-root-budget")}));
 const leaves:any[]=[];const leafCount=Math.max(4,Math.min(8,Math.round(4+3*(a.phenotype.axes.foliation.testing.value+a.phenotype.axes.foliation.documentation.value))));for(let i=0;i<leafCount;i++){const e=episodes[i%episodes.length]!,role=e.metrics.tests>e.metrics.documentation?"testing":e.metrics.documentation>e.metrics.tests?"documentation":"mixed",id=`leaf-${String(i+1).padStart(2,"0")}`,range={angle:vr(-.12,.12,"leaf-angle"),contour:vr(-.05,.05,"leaf-contour"),veins:vr(-.08,.08,"leaf-veins")};leaves.push(put({id,attachment:attachment(i),contour:role==="testing"?"serrated":"lanceolate",role,length:.16+e.salience.volume*.08,width:.05,curvature:.16,vein:{secondaryPairs:3+Math.round(e.salience.volume*3),branchAngle:.55,prominence:.65},variation:range,sampledVariation:{angle:sampleVariation(decorativeSeed,id,range.angle),contour:sampleVariation(decorativeSeed,id,range.contour),veins:sampleVariation(decorativeSeed,id,range.veins)},provenance:prov([e.id],`aster-v1:${role}-foliage`,[`phenotype.foliation.${role==="mixed"?"testing":role}`])}));mainNodes[i%mainNodes.length]!.organIds.push(id);}
 const flowers:any[]=[],branchNodes:any[]=[];for(let fi=0;fi<flowerEpisodes.length;fi++){const e=flowerEpisodes[fi]!,id=`flower-${fi+1}`,nodeIndex=Math.max(0,episodes.findIndex(x=>x.id===e.id));let support:BotanicalSceneV2["plant"]["flowers"][number]["support"]=attachment(nodeIndex);if(fi>0){const aid=`axis-branch-${fi}`,branchNode=put({id:`node-branch-${fi}-terminal`,axisId:aid,arcPosition:1,episodeId:e.id,organIds:[id],provenance:prov([e.id],"aster-v1:branch-terminal-node")});branchNodes.push(branchNode);axes.splice(1,0,put({id:aid,kind:"secondary-stem" as const,parentAttachment:{...support},chronology:{startEpisodeId:e.id,endEpisodeId:e.id},length:.3,baseRadius:.025,tipRadius:.007,taperExponent:1.3,lean:0,curvature:.2,nodeIds:[branchNode.id],supportsFeatureIds:[id],variation:{waviness:vr(-.06,.06,"branch-waviness"),bend:vr(-.1,.1,"branch-bend","structural"),torsion:vr(-.03,.03,"branch-torsion")},provenance:prov([e.id],"aster-v1:release-supporting-branch")}));mainNodes[nodeIndex]!.organIds.push(aid);support={parentAxisId:aid,arcPosition:1,tangentAngle:0,side:"front",nodeId:branchNode.id};}
 const ringCount=2,petals:any[]=[],rings:any[]=[];for(let ri=0;ri<ringCount;ri++){const count=10+ri*4,rid=`${id}-ring-${ri+1}`,range={length:vr(.9,1.1,"petal-length"),rotation:vr(-.05,.05,"petal-rotation"),curvature:vr(-.08,.08,"petal-curvature")};rings.push({id:rid,order:ri,petalCount:count,phase:ri*.12,radius:.1+ri*.04,overlap:.2,contour:ri?"ray":"spatulate",length:.14+ri*.03,basalWidth:.03,shoulderWidth:.05,taper:.7,cup:.15,reflex:.08,radialAsymmetry:.04,variation:range,provenance:prov([e.id],"aster-v1:bounded-petal-ring")});for(let pi=0;pi<count;pi++){const pid=`${rid}-petal-${String(pi+1).padStart(2,"0")}`,pv={contour:vr(-.08,.08,"petal-contour"),rotation:range.rotation};petals.push({id:pid,ringId:rid,ordinal:pi,radialAngle:(Math.PI*2*pi/count)+ri*.12,lengthScale:1,widthScale:1,cup:.15,reflex:.08,tipBias:0,variation:pv,sampledVariation:{contour:sampleVariation(decorativeSeed,pid,pv.contour),rotation:sampleVariation(decorativeSeed,pid,pv.rotation)},provenance:prov([e.id],"aster-v1:grammar-child-petal")});}}
 const florets=Array.from({length:24},(_,i)=>({id:`${id}-floret-${String(i+1).padStart(2,"0")}`,ordinal:i,radialPosition:Math.sqrt((i+.5)/24),angle:i*2.399963229728653,scale:.8,stage:"open" as const,provenance:prov([e.id],"aster-v1:bounded-phyllotactic-floret")}));flowers.push(put({id,support,episodeIds:[e.id],maturity:"mature" as const,orientation:{azimuth:0,elevation:.25},receptacle:{radius:.12,asymmetry:.03},sepals:{count:7,length:.08,spread:.45},rings,petals,center:{arrangement:"phyllotactic-florets" as const,count:24,goldenAngle:2.399963229728653,radius:.1,floretShape:"tubular" as const},florets,provenance:prov([e.id],"aster-v1:released-episode-bloom",["episode.salience.release"])}));if(fi===0)mainNodes[nodeIndex]!.organIds.push(id);}
 const buds:any[]=[];if(unreleased.length){const e=unreleased[0]!,id="bud-1";buds.push(put({id,support:attachment(episodes.indexOf(e)),maturity:.65,provenance:prov([e.id],"aster-v1:salient-unreleased-bud")}));mainNodes[episodes.indexOf(e)]!.organIds.push(id);}
 const scars=a.landmarks.filter(x=>x.kind==="revert").slice(0,3).map((x,i)=>put({id:`scar-${i+1}`,attachment:attachment(Math.min(i+1,episodes.length-1)),severity:.35,provenance:{sourceRefs:x.sourceRefs,metricRefs:[],derivation:"aster-v1:observed-revert-scar",confidence:1,capabilities:a.capabilities}}));
 axes[0].supportsFeatureIds=[...flowers.filter(x=>x.support.parentAxisId==="axis-main").map(x=>x.id),...buds.map(x=>x.id)];for(const axis of axes){axis.sampledVariation=Object.fromEntries(Object.entries(axis.variation as Record<string,VariationRange>).map(([name,range])=>[name,sampleVariation(range.class==="structural"?structuralSeed:decorativeSeed,axis.id,range)]));}for(const flower of flowers){for(const ring of flower.rings)pIndex[ring.id]=ring.provenance;for(const petal of flower.petals)pIndex[petal.id]=petal.provenance;for(const floret of flower.florets)pIndex[floret.id]=floret.provenance;}const plantProv=prov(episodes.map(e=>e.id),"aster-v1:coherent-plant");const scene:any={schemaVersion:2,grammarVersion:"botanical-grammar-v2.0.0",source:a.source,generation:{structuralSeed,decorativeSeed,prng:"xoshiro128ss-v1",scalingMode:o.scalingMode??"repository-relative",quantization:1e-4},phenotype:a.phenotype,archetype:ASTER_RECIPE,plant:{id:"plant-aster-1",habit:{stature:a.phenotype.axes.stature.value,crownSpread:.35+a.phenotype.axes.ramification.value*.45,lean:(a.phenotype.axes.collaboration.value-.5)*.15,symmetry:1-a.phenotype.axes.collaboration.value*.3,density:.35+a.phenotype.axes.tempo.value*.45,rootCrownRatio:.6},rootSystem:{primaryAxisId:"axis-root",lateralAxisIds:rootIds.slice(1),density:.55,spread:.65,depth:.7,basis:"activity-continuity",provenance:pIndex["axis-root"]},axes,nodes:[...rootNodes,...mainNodes,...branchNodes],leaves,buds,flowers,scars,knots:[],thorns:[],provenance:plantProv},provenanceIndex:pIndex,warnings:a.warnings};pIndex[scene.plant.id]=plantProv;return botanicalSceneV2Schema.parse(scene);
}
