import { z } from "zod";
import { canonicalJson } from "../../shared/canonical-json.js";
import { repositoryAnalysisV2Schema } from "../../analysis/v2/model.js";

const ref=z.object({kind:z.enum(["repository","commit","tag","ref","period"]),id:z.string().min(1)}).strict();
const metric=z.object({metricId:z.string(),value:z.number().finite(),normalization:z.enum(["raw","ratio","repository-relative","global-percentile"]),distributionVersion:z.string().optional(),inputs:z.array(ref)}).strict();
export const provenanceV2Schema=z.object({sourceRefs:z.array(ref),metricRefs:z.array(metric),summaryRef:z.string().optional(),derivation:z.string().min(1),confidence:z.number().min(0).max(1),capabilities:z.array(z.string())}).strict();
const variation=z.object({min:z.number().finite(),max:z.number().finite(),distribution:z.enum(["uniform","triangular"]),concern:z.string(),class:z.enum(["structural","decorative"])}).strict().refine(x=>x.min<=x.max);
const attachment=z.object({parentAxisId:z.string(),arcPosition:z.number().min(0).max(1),tangentAngle:z.number().finite(),side:z.enum(["left","right","front","back"]),nodeId:z.string()}).strict();
const axis=z.object({id:z.string(),kind:z.enum(["main-stem","secondary-stem","root","lateral-root"]),parentAttachment:attachment.optional(),chronology:z.object({startEpisodeId:z.string(),endEpisodeId:z.string()}).strict(),length:z.number().positive(),baseRadius:z.number().positive(),tipRadius:z.number().nonnegative(),taperExponent:z.number().positive(),lean:z.number().finite(),curvature:z.number().finite(),nodeIds:z.array(z.string()),supportsFeatureIds:z.array(z.string()),variation:z.record(variation),sampledVariation:z.record(z.number()),provenance:provenanceV2Schema}).strict();
const leaf=z.object({id:z.string(),attachment,contour:z.enum(["lanceolate","ovate","serrated","lobed"]),role:z.enum(["testing","documentation","mixed"]),length:z.number().positive(),width:z.number().positive(),curvature:z.number().finite(),vein:z.object({secondaryPairs:z.number().int().positive(),branchAngle:z.number(),prominence:z.number().min(0).max(1)}).strict(),variation:z.record(variation),sampledVariation:z.record(z.number()).optional(),provenance:provenanceV2Schema}).strict();
const petal=z.object({id:z.string(),ringId:z.string(),ordinal:z.number().int().nonnegative(),radialAngle:z.number(),lengthScale:z.number().positive(),widthScale:z.number().positive(),cup:z.number(),reflex:z.number(),tipBias:z.number(),variation:z.record(variation),sampledVariation:z.record(z.number()).optional(),provenance:provenanceV2Schema}).strict();
const ring=z.object({id:z.string(),order:z.number().int().nonnegative(),petalCount:z.number().int().positive(),phase:z.number(),radius:z.number().positive(),overlap:z.number(),contour:z.enum(["ray","spatulate","tepal"]),length:z.number().positive(),basalWidth:z.number().positive(),shoulderWidth:z.number().positive(),taper:z.number(),cup:z.number(),reflex:z.number(),radialAsymmetry:z.number(),variation:z.record(variation),provenance:provenanceV2Schema}).strict();
const flower=z.object({id:z.string(),support:attachment,episodeIds:z.array(z.string()),maturity:z.enum(["bud","opening","mature","spent"]),orientation:z.object({azimuth:z.number(),elevation:z.number()}).strict(),receptacle:z.object({radius:z.number().positive(),asymmetry:z.number()}).strict(),sepals:z.object({count:z.number().int().positive(),length:z.number().positive(),spread:z.number()}).strict(),rings:z.array(ring),petals:z.array(petal),center:z.object({arrangement:z.enum(["phyllotactic-florets","phyllotactic-seeds"]),count:z.number().int().positive(),goldenAngle:z.number(),radius:z.number().positive(),floretShape:z.enum(["tubular","seed"])}).strict(),florets:z.array(z.object({id:z.string(),ordinal:z.number().int().nonnegative(),radialPosition:z.number(),angle:z.number(),scale:z.number().positive(),stage:z.enum(["closed","open","seed"]),provenance:provenanceV2Schema}).strict()),provenance:provenanceV2Schema}).strict();
const small=<T extends z.ZodRawShape>(extra:T)=>z.object({id:z.string(),...extra,provenance:provenanceV2Schema}).strict();
const scene=z.object({schemaVersion:z.literal(2),grammarVersion:z.string(),source:repositoryAnalysisV2Schema.shape.source,generation:z.object({structuralSeed:z.string(),decorativeSeed:z.string(),prng:z.literal("xoshiro128ss-v1"),scalingMode:z.enum(["repository-relative","globally-comparable"]),quantization:z.number().positive()}).strict(),phenotype:repositoryAnalysisV2Schema.shape.phenotype,archetype:z.object({id:z.literal("aster-v1"),selectedByRule:z.string(),traits:z.object({growthHabit:z.literal("erect-herb"),inflorescence:z.literal("capitulum"),phyllotaxy:z.enum(["alternate","opposite","whorled"]),rootHabit:z.literal("taproot")}).strict(),borrowedTraits:z.array(z.object({from:z.enum(["aster-v1","lupine-v1","vine-v1"]),trait:z.string()}).strict())}).strict(),plant:z.object({id:z.string(),habit:z.object({stature:z.number().min(0).max(1),crownSpread:z.number().min(0).max(1),lean:z.number(),symmetry:z.number().min(0).max(1),density:z.number().min(0).max(1),rootCrownRatio:z.number().positive()}).strict(),rootSystem:z.object({primaryAxisId:z.string(),lateralAxisIds:z.array(z.string()),density:z.number().min(0).max(1),spread:z.number().min(0).max(1),depth:z.number().min(0).max(1),basis:z.enum(["components","dependencies","activity-continuity"]),provenance:provenanceV2Schema}).strict(),axes:z.array(axis),nodes:z.array(small({axisId:z.string(),arcPosition:z.number().min(0).max(1),episodeId:z.string(),organIds:z.array(z.string())})),leaves:z.array(leaf),buds:z.array(small({support:attachment,maturity:z.number().min(0).max(1)})),flowers:z.array(flower),scars:z.array(small({attachment,severity:z.number().min(0).max(1)})),knots:z.array(small({attachment,radius:z.number().positive()})),thorns:z.array(small({attachment,length:z.number().positive()})),provenance:provenanceV2Schema}).strict(),provenanceIndex:z.record(provenanceV2Schema),warnings:repositoryAnalysisV2Schema.shape.warnings}).strict();
const forbidden=new Set(["x","y","d","path","fill","stroke","color","font","filter","viewport"]);
function noRenderingKeys(v:unknown):boolean{if(Array.isArray(v))return v.every(noRenderingKeys);if(v&&typeof v==="object")return Object.entries(v).every(([k,x])=>!forbidden.has(k)&&noRenderingKeys(x));return true;}
export const botanicalSceneV2Schema=scene.refine(noRenderingKeys,"BotanicalSceneV2 contains renderer/style/coordinate fields");
export type BotanicalSceneV2=z.infer<typeof scene>; export type ProvenanceV2=z.infer<typeof provenanceV2Schema>;
export const serializeBotanicalSceneV2=(v:BotanicalSceneV2)=>`${canonicalJson(botanicalSceneV2Schema.parse(v))}\n`;
