#!/usr/bin/env node
import{Command}from"commander";import{readFile,writeFile}from"node:fs/promises";import{analyze}from"./analyze.js";import{portrait}from"./portrait.js";import{canonicalRepositorySchema,serializeCanonical}from"../canonical/model.js";import{botanicalSceneSchema,grow,serializeBotanical}from"../botany/model.js";import{renderSvg}from"../render/svg/index.js";
const program=new Command().name("anthesis").description("Render Git history as botanical art");
program.command("analyze").argument("<repo>").requiredOption("--output <file>").option("--full-analysis").option("--config <file>").action(async(repo:string,o:{output:string;fullAnalysis?:boolean;config?:string})=>analyze(repo,o.output,o.fullAnalysis,o.config));
program.command("grow").argument("<analysis>").requiredOption("--output <file>").option("--mvp-grammar").action(async(input:string,o:{output:string;mvpGrammar?:boolean})=>{const c=canonicalRepositorySchema.parse(JSON.parse(await readFile(input,"utf8")));await writeFile(o.output,serializeBotanical(grow(c,{enabled:o.mvpGrammar===true})));});
program.command("render").argument("<plant>").requiredOption("--analysis <file>").requiredOption("--output <file>").action(async(input:string,o:{analysis:string;output:string})=>{const c=canonicalRepositorySchema.parse(JSON.parse(await readFile(o.analysis,"utf8"))),b=botanicalSceneSchema.parse(JSON.parse(await readFile(input,"utf8"))),r=renderSvg(c,b,serializeCanonical(c),serializeBotanical(b));await Promise.all([writeFile(o.output,r.svg),writeFile(o.output.replace(/\.svg$/,".provenance.json"),r.provenance)]);});
program.command("portrait").argument("<repo>").requiredOption("--output <file>").option("--full-analysis").option("--mvp-grammar").option("--config <file>").action(async(repo:string,o:{output:string;fullAnalysis?:boolean;mvpGrammar?:boolean;config?:string})=>portrait(repo,o.output,o.fullAnalysis,o.config,o.mvpGrammar));
program.command("explain").argument("<plant>").action(async(input:string)=>{const b=botanicalSceneSchema.parse(JSON.parse(await readFile(input,"utf8")));process.stdout.write(`${JSON.stringify({phenotype:b.phenotype,elements:b.elements.map(e=>({id:e.id,kind:e.kind,sourceRefs:e.sourceRefs,metrics:e.metrics,intent:e.intent}))},null,2)}\n`);});
program.parseAsync().catch((error:unknown)=>{console.error(`anthesis: ${error instanceof Error?error.message:String(error)}`);process.exitCode=1;});
