import { sha256 } from "../../shared/canonical-json.js";
import type { CanonicalRepositoryV1 } from "../../canonical/model.js";
import type { ChangeProfile, ContributorProfile, RepositoryAnalysisV2, SourceRef } from "./model.js";
import { clamp01, median, normalizePositive, shrunkRatio, type ScalingMode } from "./normalization.js";
type Commit=CanonicalRepositoryV1["commits"][number];
const day=(a:string,b:string)=>Math.max(0,(Date.parse(b)-Date.parse(a))/86400000);
const refs=(commits:Commit[]):SourceRef[]=>commits.map(c=>({kind:"commit" as const,id:c.sha}));
function profile(commits:Commit[]):ChangeProfile{return{commits:commits.length,additions:commits.reduce((n,c)=>n+c.additions,0),deletions:commits.reduce((n,c)=>n+c.deletions,0),filesChanged:commits.reduce((n,c)=>n+c.filesChanged,0),tests:commits.reduce((n,c)=>n+c.testChanges,0),documentation:commits.reduce((n,c)=>n+c.documentationChanges,0),generated:0,formatting:0,renames:0,byComponent:[]};}
export function contributorProfile(commits:Commit[]):ContributorProfile{const counts=new Map<string,number>();for(const c of commits)counts.set(c.authorId,(counts.get(c.authorId)??0)+1);const ids=[...counts.keys()].sort(),total=commits.length;if(!total)return{count:0,effectiveCount:0,entropy:0,ids};let h=0;for(const n of counts.values()){const p=n/total;h-=p*Math.log(p);}return{count:ids.length,effectiveCount:Math.exp(h),entropy:ids.length<2?0:clamp01(h/Math.log(ids.length)),ids};}
type Group={commits:Commit[];startReason:"repository-start"|"release"|"dormancy"|"density-valley"|"landmark";endReason:"repository-end"|"release"|"dormancy"|"density-valley"|"landmark";tags:CanonicalRepositoryV1["tags"]};
type BudgetGroup=Group&{key:string;protected:boolean;protectionOverflow:boolean};
export function isQualifyingReleaseTag(name:string):boolean{return /^(?:release[-/_])?v?\d+(?:\.\d+){0,2}(?:[-+][0-9a-z.-]+)?$/i.test(name);}
export function buildEpisodes(c:CanonicalRepositoryV1,mode:ScalingMode,budget=20):Pick<RepositoryAnalysisV2,"episodes"|"summarization">{
  const gaps=c.commits.slice(1).map((x,i)=>day(c.commits[i]!.authoredAt,x.authoredAt)),med=median(gaps),dormancyThreshold=Math.max(14,med*4),valleyThreshold=Math.max(3,med*2),groups:Group[]=[];let current:Commit[]=[],nextStart:Group["startReason"]="repository-start";
  const releaseTags=c.tags.filter(t=>isQualifyingReleaseTag(t.name));
  for(let i=0;i<c.commits.length;i++){const commit=c.commits[i]!,prior=c.commits[i-1],gap=prior?day(prior.authoredAt,commit.authoredAt):0;if(current.length&&gap>valleyThreshold){const reason=gap>dormancyThreshold?"dormancy" as const:"density-valley" as const;groups.push({commits:current,startReason:nextStart,endReason:reason,tags:[]});current=[];nextStart=reason;}current.push(commit);const tags=releaseTags.filter(t=>t.occurredAt>=commit.authoredAt&&(i===c.commits.length-1||t.occurredAt<c.commits[i+1]!.authoredAt));if(tags.length){groups.push({commits:current,startReason:nextStart,endReason:"release",tags});current=[];nextStart="release";}}
  if(current.length)groups.push({commits:current,startReason:nextStart,endReason:"repository-end",tags:[]});
  const ledger:RepositoryAnalysisV2["summarization"]=[],rawMax=Math.max(1,...groups.map(g=>g.commits.reduce((n,c)=>n+c.additions+c.deletions,0))),original:BudgetGroup[]=groups.map((g,i)=>({...g,key:`raw-${i+1}`,protected:g.tags.length>0||g.commits.some(c=>c.isRevert)||g.commits.reduce((n,c)=>n+c.additions+c.deletions,0)===rawMax,protectionOverflow:false}));let bounded=[...original];
  while(bounded.length>budget){let selected=-1,selectedScore=Number.POSITIVE_INFINITY;for(let i=0;i<bounded.length-1;i++){const a=bounded[i]!,b=bounded[i+1]!;if(a.protected&&b.protected)continue;const volume=[...a.commits,...b.commits].reduce((n,c)=>n+c.additions+c.deletions,0),score=(a.protected||b.protected?1_000_000:0)+volume;if(score<selectedScore){selected=i;selectedScore=score;}}if(selected<0){for(let i=0;i<bounded.length-1;i++){const a=bounded[i]!,b=bounded[i+1]!,score=[...a.commits,...b.commits].reduce((n,c)=>n+c.additions+c.deletions,0);if(score<selectedScore){selected=i;selectedScore=score;}}}const left=bounded[selected]!,right=bounded[selected+1]!,overflow=left.protected&&right.protected;bounded.splice(selected,2,{commits:[...left.commits,...right.commits],startReason:left.startReason,endReason:right.endReason,tags:[...left.tags,...right.tags],key:`${left.key}+${right.key}`,protected:left.protected||right.protected,protectionOverflow:left.protectionOverflow||right.protectionOverflow||overflow});}
  const maxVolume=Math.max(1,...bounded.map(g=>g.commits.reduce((n,c)=>n+c.additions+c.deletions,0)));
  const episodes=bounded.map((g,index)=>{const p=profile(g.commits),cp=contributorProfile(g.commits),sourceRefs=refs(g.commits),releaseRefs=g.tags.map(t=>({kind:"tag" as const,id:t.name})).sort((a,b)=>a.id.localeCompare(b.id)),volume=p.additions+p.deletions,id=`episode-${sha256(g.commits.map(x=>x.sha).join(":" )).slice(0,12)}`,duration=Math.max(1,Math.ceil(day(g.commits[0]!.authoredAt,g.commits.at(-1)!.authoredAt)+1)),reverts=g.commits.filter(x=>x.isRevert).length,merges=g.commits.filter(x=>x.isMerge).length;return{id,ordinal:index+1,interval:{start:g.commits[0]!.authoredAt,end:g.commits.at(-1)!.authoredAt,durationDays:duration},boundary:{start:g.startReason,end:g.endReason},releaseRefs,sourceRefs,metrics:p,normalized:{changeVolume:normalizePositive(volume,maxVolume,mode),commits:normalizePositive(p.commits,Math.max(...bounded.map(x=>x.commits.length)),mode),deletionShare:{raw:p.deletions,transformed:shrunkRatio(p.deletions,volume),repositoryRelative:shrunkRatio(p.deletions,volume),clipped:false,confidence:clamp01(volume/4)}},contributors:cp,salience:{release:releaseRefs.length?1:0,volume:clamp01(Math.log1p(volume)/Math.log1p(maxVolume)),contributorNovelty:cp.entropy,topology:clamp01(merges),reversal:clamp01(reverts),categoryShift:clamp01((p.tests+p.documentation)/Math.max(1,p.filesChanged)),duration:clamp01(duration/90),protected:g.protected&&!g.protectionOverflow},character:[p.deletions>p.additions?"renewal" as const:undefined,cp.count>1?"collaborative" as const:undefined,p.documentation>p.tests&&p.documentation?"documentary" as const:undefined,p.tests>=p.documentation&&p.tests?"testing" as const:undefined,p.commits>5?"burst" as const:"steady" as const].filter((x):x is NonNullable<typeof x>=>!!x),status:releaseRefs.length?"released" as const:"unreleased" as const,summarizedFrom:g.key.split("+"),provenance:{sourceRefs,metricRefs:[],summaryRef:`summary-${id}`,derivation:"episodes-v1",confidence:g.protectionOverflow?.75:1,capabilities:["reachable-commits"]}};});
  for(const episode of episodes)ledger.push({id:`summary-${episode.id}`,operation:episode.summarizedFrom.length>1?"coalesce-budget":"cluster",inputRefs:episode.sourceRefs,inputEpisodeIds:episode.summarizedFrom,outputEpisodeIds:[episode.id],reasonCode:episode.summarizedFrom.length>1?"visual-budget":"chronological-cluster",discardedDetail:["per-commit-shape"]});
  for(const e of episodes.filter(x=>x.salience.protected))ledger.push({id:`protect-${e.id}`,operation:"protect-landmark",inputRefs:[...e.sourceRefs,...e.releaseRefs],inputEpisodeIds:[e.id],outputEpisodeIds:[e.id],reasonCode:"release-revert-or-volume-landmark",discardedDetail:[]});
  for(const g of bounded.filter(x=>x.protectionOverflow)){const e=episodes[bounded.indexOf(g)]!;ledger.push({id:`overflow-${e.id}`,operation:"coalesce-budget",inputRefs:[...e.sourceRefs,...e.releaseRefs],inputEpisodeIds:e.summarizedFrom,outputEpisodeIds:[e.id],reasonCode:"protected-landmarks-exceed-visual-budget",discardedDetail:["minor-landmark"]});}
  return{episodes,summarization:ledger};
}
