import {z} from "zod";
import type {BotanicalSceneV2} from "../../../botany/v2/model.js";
import type {GeometrySceneV2} from "../../../geometry/v2/model.js";
import {canonicalJson,sha256} from "../../../shared/canonical-json.js";
import type {StyleTokensV1} from "../../../style/model.js";

export const svgProvenanceV2Schema=z.object({schemaVersion:z.literal(2),project:z.literal("Anthesis"),repository:z.string(),snapshotSha:z.string(),artifactHashes:z.object({canonical:z.string(),analysis:z.string(),botanical:z.string(),geometry:z.string()}).strict(),versions:z.object({grammar:z.string(),episodeAlgorithm:z.string(),normalization:z.string(),archetypeRules:z.string(),compositionSolver:z.string(),geometry:z.string(),style:z.string(),renderer:z.string(),prng:z.string()}).strict(),configurationHash:z.string(),structuralSeed:z.string(),decorativeSeed:z.string(),scalingMode:z.enum(["repository-relative","globally-comparable"]),semanticFingerprint:z.string()}).strict();
export type SvgProvenanceV2=z.infer<typeof svgProvenanceV2Schema>;
export function createProvenance(scene:BotanicalSceneV2,geometry:GeometrySceneV2,style:StyleTokensV1,inputs:{analysisBytes:string;botanicalBytes:string;geometryBytes:string}):SvgProvenanceV2{return svgProvenanceV2Schema.parse({schemaVersion:2,project:"Anthesis",repository:scene.source.repositoryIdentity,snapshotSha:scene.source.snapshotSha,artifactHashes:{canonical:scene.source.canonicalSha256,analysis:sha256(inputs.analysisBytes),botanical:sha256(inputs.botanicalBytes),geometry:sha256(inputs.geometryBytes)},versions:{grammar:scene.grammarVersion,episodeAlgorithm:"development-episodes-v2",normalization:"normalization-v2",archetypeRules:scene.archetype.selectedByRule,compositionSolver:geometry.composition.solverVersion,geometry:geometry.geometryVersion,style:style.version,renderer:"authoritative-svg-v2.0.0",prng:scene.generation.prng},configurationHash:scene.source.configHash,structuralSeed:scene.generation.structuralSeed,decorativeSeed:scene.generation.decorativeSeed,scalingMode:scene.generation.scalingMode,semanticFingerprint:geometry.semanticFingerprint});}
export const serializeSvgProvenanceV2=(p:SvgProvenanceV2)=>`${canonicalJson(svgProvenanceV2Schema.parse(p))}\n`;
