import { z } from "zod";
import type { CanonicalRepositoryV1 } from "../canonical/model.js";
import { canonicalJson, sha256 } from "../shared/canonical-json.js";
import { clamp } from "../analysis/index.js";
const sourceRef = z.object({ kind: z.enum(["commit", "tag", "period", "repository"]), id: z.string() });
export const botanicalSceneSchema = z.object({ schemaVersion: z.literal(1), grammarVersion: z.string(), source: z.object({ repositoryIdentity: z.string(), snapshotSha: z.string().regex(/^[0-9a-f]{40}$/), canonicalConfigHash: z.string().regex(/^[0-9a-f]{64}$/) }), generation: z.object({ seed: z.string(), scalingMode: z.enum(["repository-relative", "globally-comparable"]) }), phenotype: z.object({ activity: z.number().min(0).max(1), growth: z.number().min(0).max(1), pruning: z.number().min(0).max(1), branching: z.number().min(0).max(1), collaboration: z.number().min(0).max(1), review: z.number().min(0).max(1), stability: z.number().min(0).max(1), resolution: z.number().min(0).max(1), testing: z.number().min(0).max(1), documentation: z.number().min(0).max(1) }), viewport: z.object({ width: z.number(), height: z.number() }), elements: z.array(z.object({ id: z.string(), kind: z.enum(["root","stem","branch","leaf","bud","flower","petal","seed","scar","thorn"]), parentId: z.string().optional(), sourceRefs: z.array(sourceRef), metrics: z.record(z.number()), intent: z.record(z.union([z.number(), z.string(), z.boolean()])) })), warnings: z.array(z.object({ code: z.string(), message: z.string() })) }).strict();
export type BotanicalSceneV1 = z.infer<typeof botanicalSceneSchema>;
export function grow(c: CanonicalRepositoryV1): BotanicalSceneV1 { const changes = c.commits.reduce((n,x)=>n+x.additions+x.deletions,0); const seed=sha256(`${c.repository.identity}:${c.repository.snapshotSha}:${c.analysis.configHash}:stage-0`); const base={activity:clamp(c.commits.length/10),growth:clamp(changes/100),pruning:clamp(c.commits.reduce((n,x)=>n+x.deletions,0)/100),branching:0,collaboration:clamp(c.contributors.length/5),review:0,stability:1,resolution:1,testing:clamp(c.commits.reduce((n,x)=>n+x.testChanges,0)/5),documentation:clamp(c.commits.reduce((n,x)=>n+x.documentationChanges,0)/5)}; return botanicalSceneSchema.parse({schemaVersion:1,grammarVersion:"stage-0-v1",source:{repositoryIdentity:c.repository.identity,snapshotSha:c.repository.snapshotSha,canonicalConfigHash:c.analysis.configHash},generation:{seed,scalingMode:"repository-relative"},phenotype:base,viewport:{width:800,height:1000},elements:[{id:"main-stem",kind:"stem",sourceRefs:c.commits.map(x=>({kind:"commit" as const,id:x.sha})),metrics:{commitCount:c.commits.length},intent:{height:0.72}},...c.tags.map((t,i)=>({id:`flower-${i+1}`,kind:"flower" as const,parentId:"main-stem",sourceRefs:[{kind:"tag" as const,id:t.name}],metrics:{tagIndex:i},intent:{label:t.name,position:0.75}}))],warnings:[]}); }
export function serializeBotanical(v: BotanicalSceneV1): string { return `${canonicalJson(botanicalSceneSchema.parse(v))}\n`; }
