import test from "node:test";
import assert from "node:assert/strict";
import type { CanonicalRepositoryV1 } from "../../src/canonical/model.js";
import { analyzeRepositoryV2, repositoryAnalysisV2Schema, serializeRepositoryAnalysisV2 } from "../../src/analysis/v2/index.js";

function history(count:number,options:{tags?:number;dormancy?:boolean;sameTime?:boolean;outlier?:boolean}={}):CanonicalRepositoryV1{
  const commits=Array.from({length:count},(_,i)=>{const day=options.sameTime?1:1+i+(options.dormancy&&i>=Math.ceil(count/2)?90:0);return{sha:i.toString(16).padStart(40,"0"),parentShas:i?[`${(i-1).toString(16).padStart(40,"0")}`]:[],authorId:`author-${i%3}`,authoredAt:new Date(Date.UTC(2024,0,day)).toISOString(),additions:options.outlier&&i===count-1?1_000_000:i+1,deletions:i%4,filesChanged:1,testChanges:i%5===0?1:0,documentationChanges:i%7===0?1:0,excludedChanges:0,isMerge:i%11===0&&i>0,isRevert:i===Math.floor(count/2)};});
  commits.sort((a,b)=>a.authoredAt.localeCompare(b.authoredAt)||a.sha.localeCompare(b.sha));
  const tagCount=options.tags??0,tags=Array.from({length:tagCount},(_,i)=>{const target=commits[Math.min(commits.length-1,Math.floor((i+1)*commits.length/tagCount)-1)]!;return{name:`v${i+1}`,targetSha:target.sha,occurredAt:target.authoredAt};}).sort((a,b)=>a.occurredAt.localeCompare(b.occurredAt)||a.name.localeCompare(b.name));
  return{schemaVersion:1,repository:{identity:"synthetic",defaultBranch:"main",snapshotSha:commits.at(-1)!.sha},analysis:{mode:"git-only",generatedAt:commits.at(-1)!.authoredAt,configHash:"a".repeat(64),exclusions:[]},period:{start:commits[0]!.authoredAt,end:commits.at(-1)!.authoredAt},contributors:[...new Set(commits.map(x=>x.authorId))].sort().map(id=>({id,displayName:id,aliases:[]})),commits,tags,warnings:[]};
}

for(const count of [1,3,8,20,60])test(`v2 analysis is valid, bounded, and complete for ${count} units`,()=>{const canonical=history(count,{tags:count===60?8:Math.min(2,count)}),one=analyzeRepositoryV2(canonical,{visualBudget:20}),two=analyzeRepositoryV2(canonical,{visualBudget:20});repositoryAnalysisV2Schema.parse(one);assert.equal(serializeRepositoryAnalysisV2(one),serializeRepositoryAnalysisV2(two));assert.ok(one.episodes.length<=20);assert.deepEqual(one.episodes.map(x=>x.ordinal),Array.from({length:one.episodes.length},(_,i)=>i+1));const covered=new Set(one.episodes.flatMap(x=>x.sourceRefs.filter(r=>r.kind==="commit").map(r=>r.id)));assert.deepEqual([...covered].sort(),canonical.commits.map(x=>x.sha).sort());assert.ok(one.landmarks.filter(x=>x.protected).every(x=>one.summarization.some(s=>s.inputRefs.some(r=>x.sourceRefs.some(l=>l.kind===r.kind&&l.id===r.id)))));if(count===60){for(const landmark of one.landmarks){const owners=one.episodes.filter(e=>landmark.sourceRefs.some(l=>e.sourceRefs.some(r=>r.kind===l.kind&&r.id===l.id)||e.releaseRefs.some(r=>r.kind===l.kind&&r.id===l.id)));assert.equal(owners.length,1,`${landmark.kind} has a distinct episode owner`);assert.equal(owners[0]!.salience.protected,true);assert.equal(owners[0]!.summarizedFrom.length,1,`${landmark.kind} raw episode was not coalesced`);}}});

test("dormancy, no releases, post-release work, same-time commits, and outliers remain deterministic",()=>{for(const canonical of [history(8,{dormancy:true}),history(8),history(8,{tags:1}),history(8,{sameTime:true}),history(8,{outlier:true})]){const value=analyzeRepositoryV2(canonical);assert.ok(value.episodes.length);assert.ok(value.episodes.every(e=>Object.values(e.normalized).every(n=>Number.isFinite(n.repositoryRelative)&&n.repositoryRelative>=0&&n.repositoryRelative<=1)));assert.equal(value.episodes.at(-1)!.sourceRefs.at(-1)!.id,canonical.commits.at(-1)!.sha);}});

test("scaling modes record distinct bases and never emit a quality score",()=>{const canonical=history(8,{outlier:true}),relative=analyzeRepositoryV2(canonical),global=analyzeRepositoryV2(canonical,{scalingMode:"globally-comparable"});assert.equal(relative.episodes[0]!.normalized.commits!.globalPercentile,undefined);assert.equal(typeof global.episodes[0]!.normalized.commits!.globalPercentile,"number");assert.equal(global.episodes[0]!.provenance.metricRefs[0]!.distributionVersion,"anthesis-git-v1");assert.equal(global.phenotype.noOverallScore,true);assert.equal("score" in global.phenotype,false);assert.notEqual(relative.source.configHash,global.source.configHash);});

test("only qualifying release tags segment and release episodes",()=>{const canonical=history(8);canonical.tags=[{name:"docs-preview",targetSha:canonical.commits[2]!.sha,occurredAt:canonical.commits[2]!.authoredAt},{name:"v1.2.0",targetSha:canonical.commits[5]!.sha,occurredAt:canonical.commits[5]!.authoredAt}];const value=analyzeRepositoryV2(canonical);assert.deepEqual(value.releases.map(x=>x.name),["v1.2.0"]);assert.deepEqual(value.episodes.flatMap(x=>x.releaseRefs.map(r=>r.id)),["v1.2.0"]);assert.equal(value.episodes.some(x=>x.releaseRefs.some(r=>r.id==="docs-preview")),false);assert.ok(value.warnings.some(x=>x.code==="NON_RELEASE_TAGS_IGNORED"));});

test("protected overflow is explicit when landmarks exceed the budget",()=>{const value=analyzeRepositoryV2(history(20,{tags:20}),{visualBudget:3});assert.equal(value.episodes.length,3);assert.ok(value.summarization.some(x=>x.reasonCode==="protected-landmarks-exceed-visual-budget"&&x.discardedDetail.includes("minor-landmark")));assert.ok(value.episodes.some(x=>x.salience.protected===false));});

test("unsupported facts are absent capabilities and explicit exclusions",()=>{const value=analyzeRepositoryV2(history(3));for(const fact of ["branch-refs","unmerged-refs","components","dependencies"])assert.equal(value.capabilities.includes(fact as never),false);assert.ok(value.exclusions.unsupported.includes("dependencies"));});
