import test from "node:test";import assert from "node:assert/strict";import{readFile}from"node:fs/promises";import{resolve}from"node:path";
import{repositoryAnalysisV2Schema}from"../../src/analysis/v2/model.js";import{botanicalSceneV2Schema,interpretAster,namedStream,semanticFingerprint,serializeBotanicalSceneV2}from"../../src/botany/v2/index.js";
const fixture=resolve("test/fixtures/botanical-v2/six-episode-analysis.json");
async function analysis(){return repositoryAnalysisV2Schema.parse(JSON.parse(await readFile(fixture,"utf8")));}

test("xoshiro128** pinned vector and named streams are isolated",()=>{const p=namedStream("seed","feature","concern");assert.deepEqual(Array.from({length:5},()=>p.nextUint32()),[3133907633,3865861360,1851100391,3188766717,3297661996]);const a=namedStream("seed","feature","a").nextUint32(),b=namedStream("seed","feature","b").nextUint32();assert.notEqual(a,b);assert.equal(a,namedStream("seed","feature","a").nextUint32());});
test("six episodes grow a contract-valid coherent Aster deterministically",async()=>{const input=await analysis(),one=interpretAster(input,{structuralSeed:"structure",decorativeSeed:"ink"}),two=interpretAster(input,{structuralSeed:"structure",decorativeSeed:"ink"});assert.equal(serializeBotanicalSceneV2(one),serializeBotanicalSceneV2(two));assert.equal(one.archetype.id,"aster-v1");assert.equal(one.plant.rootSystem.lateralAxisIds.length,4);assert.ok(one.plant.axes.some(x=>x.kind==="secondary-stem"));assert.ok(one.plant.leaves.length>=4&&one.plant.leaves.length<=8);assert.ok(one.plant.flowers.length+one.plant.buds.length>=1&&one.plant.flowers.length+one.plant.buds.length<=3);assert.ok(one.plant.flowers.every(x=>x.sepals.count>0&&x.rings.length>1&&x.petals.length>0&&x.florets.length>0));assert.deepEqual(one.plant.nodes.filter(x=>(x as typeof x&{axisId:string}).axisId==="axis-main").map(x=>(x as typeof x&{episodeId:string}).episodeId),input.episodes.map(x=>x.id));assert.ok(one.plant.axes.every((x,i)=>i===0||x.parentAttachment===undefined||one.plant.axes.slice(0,i).some(p=>p.id===x.parentAttachment?.parentAxisId)||x.parentAttachment.parentAxisId==="axis-main"));botanicalSceneV2Schema.parse(one);});
test("decorative seed changes only eligible samples, never semantics",async()=>{const input=await analysis(),a=interpretAster(input,{structuralSeed:"structure",decorativeSeed:"a"}),b=interpretAster(input,{structuralSeed:"structure",decorativeSeed:"b"});assert.equal(semanticFingerprint(a),semanticFingerprint(b));assert.deepEqual(a.plant.axes.map(x=>[x.id,x.kind,x.parentAttachment,x.chronology]),b.plant.axes.map(x=>[x.id,x.kind,x.parentAttachment,x.chronology]));assert.deepEqual(a.plant.nodes,b.plant.nodes);assert.notDeepEqual(a.plant.leaves.map(x=>x.sampledVariation),b.plant.leaves.map(x=>x.sampledVariation));});
test("scene boundary rejects renderer, style, and coordinate fields",async()=>{const scene=interpretAster(await analysis()),bad=structuredClone(scene) as any;bad.plant.x=10;assert.throws(()=>botanicalSceneV2Schema.parse(bad));});
test("support topology has truthful axis ownership and valid tangent-relative nodes",async()=>{const scene=interpretAster(await analysis()),axes=new Map(scene.plant.axes.map(x=>[x.id,x])),nodes=new Map(scene.plant.nodes.map(x=>[x.id,x])),features=new Map([...scene.plant.axes,...scene.plant.flowers,...scene.plant.buds].map(x=>[x.id,x]));for(const axis of scene.plant.axes){for(const id of axis.supportsFeatureIds){assert.ok(features.has(id),`${axis.id} supports missing ${id}`);const organ=scene.plant.flowers.find(x=>x.id===id)??scene.plant.buds.find(x=>x.id===id);if(organ)assert.equal(organ.support.parentAxisId,axis.id);}if(axis.parentAttachment){const node=nodes.get(axis.parentAttachment.nodeId) as typeof scene.plant.nodes[number]&{axisId:string};assert.equal(node.axisId,axis.parentAttachment.parentAxisId);assert.ok(axes.has(axis.parentAttachment.parentAxisId));if(axis.kind==="secondary-stem"){assert.equal(axis.parentAttachment.parentAxisId,"axis-main");assert.ok(Number.isFinite(axis.parentAttachment.tangentAngle));}}}for(const organ of [...scene.plant.flowers,...scene.plant.buds,...scene.plant.leaves]){const node=nodes.get(("support"in organ?organ.support:organ.attachment).nodeId) as typeof scene.plant.nodes[number]&{axisId:string};assert.equal(node.axisId,("support"in organ?organ.support:organ.attachment).parentAxisId);}});
test("major feature provenance is indexed and metric evidence is factual",async()=>{const input=await analysis(),scene=interpretAster(input),features:any[]=[scene.plant,...scene.plant.axes,...scene.plant.nodes,...scene.plant.leaves,...scene.plant.buds,...scene.plant.flowers,...scene.plant.scars,...scene.plant.flowers.flatMap(x=>[...x.rings,...x.petals,...x.florets])];for(const feature of features){assert.ok(feature.provenance.sourceRefs.length,`${feature.id} source refs`);assert.ok(feature.provenance.derivation,`${feature.id} derivation`);assert.ok(feature.provenance.confidence>0,`${feature.id} confidence`);assert.deepEqual(scene.provenanceIndex[feature.id],feature.provenance,`${feature.id} index`);}const main=scene.plant.axes.find(x=>x.id==="axis-main")!,leaf=scene.plant.leaves.find(x=>x.role==="documentation")!,bloom=scene.plant.flowers[0]!,root=scene.plant.axes.find(x=>x.id==="axis-root")!;assert.equal(main.provenance.metricRefs[0]?.value,input.phenotype.axes.stature.value);assert.equal(leaf.provenance.metricRefs[0]?.value,input.phenotype.axes.foliation.documentation.value);assert.equal(bloom.provenance.metricRefs[0]?.value,input.episodes.find(x=>x.id===bloom.episodeIds[0])?.salience.release);assert.equal(root.provenance.metricRefs.length,0);assert.equal(scene.plant.provenance.metricRefs.length,0);});
test("default seeds are exactly stable and sensitive to analysis configHash",async()=>{const input=await analysis(),a=interpretAster(input),b=interpretAster(input),changed=structuredClone(input);changed.source.configHash="f".repeat(64);const c=interpretAster(changed);assert.deepEqual(a.generation,b.generation);assert.notEqual(a.generation.structuralSeed,c.generation.structuralSeed);assert.notEqual(a.generation.decorativeSeed,c.generation.decorativeSeed);});
